### ISSUE TITLE
Add link to download the correct version of Raspbian

### ISSUE THREAD

**Issue by oscarbailey-xmos** [xmos/vocalfusion-rpi-setup#22]
Raspbian has moved on since we last tested this setup, we should link to a version of Raspbian that works.

The Raspberry Pi foundation hosts all old images here: https://downloads.raspberrypi.org/raspbian/images/

I'm testing with raspbian-2018-10-09, but any Raspbian stretch should work.

**Comment by DaveAtkinsonXMOS** [comment]
I think this is addressed by #30

**Comment by DaveAtkinsonXMOS** [comment]
This issue is closed by #30
