### ISSUE TITLE
Linux 5.10 support - Migrating userland tools

### ISSUE THREAD

**Issue by j1nx** [xmos/vocalfusion-rpi-setup#33]
I am a developer of the opensource project OpenVoiceOS and curretnly working on supporting the sj201 HAT within the Mark2 Devkit device from the Mycroft A.I. company.

OpenVoiceOS runs the latest 5.10 LTS kernel version and the old loader didn't work as it should. So I started working on get getting it to work on 5.10 (and possibly 5.x later on) and while at it, converting it to be loaded via dtoverlay, together with migrating the userland tools into the same driver.

At the moment I have the xvf3510 working on linux 5.10 which now ships with the development alpha releases of OpenVoiceOS. When I have a bit more time I will work on the other todo's and support the other HAT versions.

Bare in mind, I am not a C programmer nor do I have any linux driver experience, so all is done by learning on the spot with some Google-Fu and reading a lot through the linux source code to learn from other drivers / programmers.

Here is the code in it's current state;
https://github.com/OpenVoiceOS/VocalFusionDriver

**Comment by mbanth** [comment]
Hello @j1nx,

Thanks for raising this issue.  At present, XMOS only provides VocalFusion RPI Setup for use with the Raspberry Pi OS.  However, we're pleased that the OpenVoiceOS is seeking to integrate our VocalFusion products with it.  Thank you for doing so.

Given our decision to currently support only Raspberry Pi OS and that version 5.15 of the Linux kernel allows the driver in question to build and load, we will not take any action on this issue at this time.
