### ISSUE TITLE
Not finding modules in /etc/modules

### ISSUE THREAD

**Issue by BillTJbl** [xmos/vocalfusion-rpi-setup#4]
In the "setup.sh" script, the following modules are added to "/etc/modules": snd_soc_bcm2708, snd_soc_bcm2708_i2s, and bcm2708_dmaengine. However they are no where in the file system. Also, early in the boot I get a module load error. If I remove these modules from "/etc/modules", the error during boot goes away and the sample app seems to work anyway.

Are these files relics from jessie?

Thanks,
Bill

**Comment by larry-xmos** [comment]
Yes, I think they are. The setup procedure now assumes Raspbian Stretch so we should remove these from the script.

Thank you for the report

**Comment by larry-xmos** [comment]
Addressed in pull request #8
