### ISSUE TITLE
Add support for XVF3800

### ISSUE THREAD

**Issue by mbanth** [xmos/vocalfusion-rpi-setup#53]
Make the necessary changes so that a customer using a Raspberry Pi coupled with an XVF3800 can use this repository to set up the Raspberry Pi correctly and easily.

**Comment by mbanth** [comment]
@lucianomartin, please provide a Story Point value for this issue.  Thanks.

**Comment by ed-xmos** [comment]
Note I have done this as part of https://github.com/xmos/sw_xvf3800/issues/318

**Comment by ed-xmos** [comment]
This config has now passed using @shuchitak 's test PR on dut-2 and dut-3 so considering this one closed
