### ISSUE TITLE
setup.sh xvf3800-intdev failed on a Pi4

### ISSUE THREAD

**Issue by uvvpavel** [xmos/vocalfusion-rpi-setup#75]
I've followed instructions from https://github.com/xmos/vocalfusion-rpi-setup/blob/release/v5.8.0/README.md and the script has failed with a weird error something with /lib/modules. I found that this combination of commands worked for me.
```
sudo sh -c "echo 'arm_64bit=0' >> /boot/config.txt"
sudo reboot
sudo apt update
sudo apt upgrade
sudo apt-get install --reinstall raspberrypi-bootloader raspberrypi-kernel
sudo reboot
./setup.sh xvf3800-intdev
```

**Comment by xluciano** [comment]
The instructions in this release branch should fix the issue. See this [readme file](https://github.com/xmos/vocalfusion-rpi-setup/blob/release/v5.8.0/README.md).

**Comment by mbanth** [comment]
@uvvpavel, please try the suggestion made by @lucianomartin.  If you still see the same problem, please discuss with @lucianomartin and the two of you set a Story Point value for this issue.  Thanks.

**Comment by xluciano** [comment]
I have successfully configured both a Pi3 and a Pi4 by following the steps in https://github.com/xmos/vocalfusion-rpi-setup/blob/release/v5.8.0/README.md.
As @uvvpavel advised, we should add a reboot step after the update/upgrade operations, so that the procedure is safer.

**Comment by xluciano** [comment]
Re-open to track PR to master
